name: "Nginx WebDAV"
description: "Provides media access over WebDAV"
version: "0.0.3"
slug: "nginx-webdav"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: 80
map:
  - type: share
    read_only: False
    path: /data/shared
