name: "FRP Client"
description: "Fast Reverse Proxy client"
version: "0.0.4"
slug: "frp-client"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: addon_config
    read_only: False
    path: /config
