name: "MiniDLNA"
description: "Shares media via DLNA protocol"
version: "0.0.6"
slug: "minidlna"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8200/tcp: 8200
  1900/udp: 1900
map:
  - type: media
    read_only: False
    path: /opt
  - type: addon_config
    read_only: False
    path: /config/
