name: "MiniDLNA"
description: "Shares media via DLNA protocol"
version: "0.0.9"
slug: "minidlna"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
map:
  - type: media
    read_only: False
    path: /opt
  - type: addon_config
    read_only: False
    path: /config/
webui: "http://[HOST]:[PORT:8200]"