name: "Transmission Daemon"
description: "Provides UI for downloading media by torrent protocol"
version: "0.0.3"
slug: "transmission-daemon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9091/tcp: 9091
map:
  - type: media
    read_only: False
    path: /transmission/downloads/
  - type: share
    read_only: False
    path: /transmission/incomplete/
  - type: addon_config
    read_only: False
    path: /transmission/config/
ingress: true
ingress_port: 9091
