name: "Transmission Daemon"
description: "Provides UI for downloading media by torrent protocol"
version: "0.0.7"
slug: "transmission-daemon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9091/tcp: 9091
map:
  - type: media
    read_only: False
    path: /transmission/downloads/
  - type: share
    read_only: False
    path: /transmission/incomplete/
  - type: addon_config
    read_only: False
    path: /transmission/config/
options:
  proxy_enabled: false
  proxy_url: ""
  no_proxy: "127.0.0.1,localhost"
schema:
  proxy_enabled: bool
  proxy_url: "str?"
  no_proxy: "str?"
